#ifndef VERSIONRC_H
#define VERSIONRC_H

#include "version.h"

#define STRINIFY(s) #s

#define VER_PRODUCTVERSION     CLIENT_VERSION_MAJOR,CLIENT_VERSION_MINOR,CLIENT_VERSION_REVISION,CLIENT_VERSION_BUILD
#define VER_PRODUCTVERSION_STR STRINGIFY(CLIENT_VERSION_MAJOR) "." STRINGIFY(CLIENT_VERSION_MINOR) "." STRINGIFY(CLIENT_VERSION_REVISION) "." STRINGIFY(CLIENT_VERSION_BUILD)

#endif // VERSIONRC_H
